version: '3.3'

services:
  # web-api:
  #   image: web-app
  #   container_name: web-app
  #   build: .
  #   environment:
  #     DB_HOST: localhost
  #     DB_PORT: 3060
  #     DB_USER: ton
  #     DB_PASSWORD: 112233
  #     DB_DATABASE: DB_THAI_CAMPS
  #   ports:
  #     - 1100:4000
  #   depends_on:
  #     - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 112233
      MYSQL_DATABASE: DB_THAI_CAMPS
      MYSQL_USER: ton
      MYSQL_PASSWORD: 112233
    ports:
      - 3060:3306
    networks:
      - database
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - database
networks:
  database:
    driver: bridge
