version: '3.3'

services:
  # mysql:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: p@ssw0rd1112234
  #     MYSQL_DATABASE: DB_THAI_CAMPS
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - application

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: mysql
  #   networks:
  #     - application

  web-api:
    image: web-app
    restart: always
    container_name: web-app
    build: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: p@ssw0rd1112234
      DB_DATABASE: DB_THAI_CAMPS
      NODE_ENV: production
    ports:
      - 122:4000
    depends_on:
      - mysql
    networks:
      - application

networks:
  application:
    driver: bridge