-- สร้างตารางเกี่ยวกับข้อมูล Preference
CREATE TABLE IF NOT EXISTS TB_PREFERENCE (
    ID_PREFERENCE INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL
);

-- สร้างตารางเกี่ยวกับข้อมูลประเทศ
CREATE TABLE IF NOT EXISTS TB_COUNTRY (
    ID_COUNTRY INT AUTO_INCREMENT PRIMARY KEY,
    NAME_COUNTRY VARCHAR(100) NOT NULL,
    CODE_COUNTRY VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL
);
