-- USER
CREATE TABLE IF NOT EXISTS TB_USER(
    ID_USER VARCHAR(50)  PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    IMAGE VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ID_EMAIL VARCHAR(100) NOT NULL,
    ID_FACEBOOK VARCHAR(100) NOT NULL,
    ID_GITHUB VARCHAR(100) NOT NULL,
    ID_IG VARCHAR(100) NOT NULL,
    ID_LINE VARCHAR(100) NOT NULL,
    ID_LINE_NAME VARCHAR(100) NOT NULL,
    LOGIN_BY ENUM("SYSTEM", "GMAIL", "FACEBOOK", "GITHUB", "IG", "LINE") DEFAULT "SYSTEM",
    STATUE ENUM("PUBLIC", "PRIVATE") DEFAULT "PUBLIC",
    ACTIVE_TYPE ENUM("USER","COMPANY","ADVERTISER","ADMIN") DEFAULT "USER",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
);

CREATE TABLE IF NOT EXISTS TB_COMPANY(
    ID_COMPANY VARCHAR(50) PRIMARY KEY,
    ID_USER VARCHAR(50),
    COMPANY_NAME VARCHAR(255),
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    WEBPAGE VARCHAR(100) NOT NULL,
    ID_LINE VARCHAR(50) NOT NULL,
    IMAGE_PROFILE VARCHAR(50) NOT NULL,
    IMAGE_COVER VARCHAR(50) NOT NULL,
    -- meta
    TITLE VARCHAR(100) NOT NULL,
    META_DESCRIPTION VARCHAR(100) NOT NULL,
    META_KEYWORDS VARCHAR(100) NOT NULL,
    -- facebook
    OPENGRAPH_TITLE VARCHAR(100) NOT NULL,
    OPENGRAPH_DESCRIPTION VARCHAR(100) NOT NULL,
    OPENGRAPH_URL_IMAGES VARCHAR(100) NOT NULL,
    -- twitter
    TWITTER_TITLE VARCHAR(100) NOT NULL,
    TWITTER_DESCRIPTION VARCHAR(100) NOT NULL,
    TWITTER_URL_IMAGES VARCHAR(100) NOT NULL,
    
    STATUS_COMPANY ENUM("PENDING","NORMAL","VERIFY","PREMIER") DEFAULT "PENDING",
    STATUS ENUM("PUBLIC","PRIVATE") DEFAULT "PUBLIC",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);


CREATE TABLE IF NOT EXISTS TB_USER_POST(
    ID_USER_POST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50),
    TITLE VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(50) NOT NULL,
    VIDEO VARCHAR(50) NOT NULL,
    LINK_VIDEO VARCHAR(100) NOT NULL,
    TYPE_UPLOAD ENUM("TEXT", "IMAGE", "VIDEO","LINKVIDEO") DEFAULT "TEXT",
    TYPE_POST ENUM("NORMAL","SHARE") DEFAULT "NORMAL",
    IS_SHARE BOOLEAN DEFAULT TRUE,
    IS_COMMENT BOOLEAN DEFAULT TRUE,
    REFERENCES_ID_USER_POST INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID_USER)
);


-- ใช้ได้ทั้ง user post และ company post
CREATE TABLE IF NOT EXISTS TB_USER_COMMENT_POST(
    ID_USER_COMMENT_POST INT AUTO_INCREMENT PRIMARY KEY,
    PARENT_ID INT, -- เก็บ post หรือ comment เลยไม่ใส่ forent key
    PERSION_ID VARCHAR(50), -- เก็บข้อมูลว่าใครเป็นคน like user หรือ compay เลยไม่ใส่ foreing key
    COMMENT VARCHAR(255) NOT NULL,
    ID_USER VARCHAR(50),
    COMMENT_TO ENUM("POST","COMMENT") DEFAULT "POST",
    PERSON_COMMENT ENUM("USER", "COMPANY") DEFAULT "USER",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ใช้ได้ทั้ง user post และ company post
CREATE TABLE IF NOT EXISTS TB_USER_LIKE_POST(
    ID_USER_LIKE_POST INT AUTO_INCREMENT PRIMARY KEY,
    PARENT_ID INT, -- เก็บ post หรือ comment เลยไม่ใส่ foreing key
    PERSION_ID VARCHAR(50), -- เก็บข้อมูลว่าใครเป็นคน like user หรือ compay เลยไม่ใส่ foreing key
    LIKE_TO ENUM("POST","COMMENT") DEFAULT "POST",
    PERSON_LIKE ENUM("USER", "COMPANY") DEFAULT "USER",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT NULL
);

 -- กด ติดตามใน post 
CREATE TABLE IF NOT EXISTS TB_USER_FAVORITE_POST(
    ID_USER_FAVORITE_POST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_POST INT,
    ID_USER VARCHAR(50),
    ID_COMPANY VARCHAR(50),
    ID_FAVORITE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PERSON_FAVORITE ENUM("USER", "COMPANY") DEFAULT "USER",
    FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID_USER),
    FOREIGN KEY (ID_USER_POST) REFERENCES TB_USER_POST(ID_USER_POST),
    FOREIGN KEY (ID_COMPANY) REFERENCES TB_COMPANY (ID_COMPANY)
);



CREATE TABLE IF NOT EXISTS TB_TYPE_USER_BLACKLIST(
    ID_TYPE_USER_BLACKLIST INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
);

CREATE TABLE IF NOT EXISTS TB_USER_BLACKLIST(
    ID_USER_BLACKLIST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_REPORTING VARCHAR(50),
    ID_USER_REPORTER VARCHAR(50),
    ID_TYPE_USER_BLACKLIST INT,
    STATUS_BLACKLIST ENUM("PENDING", "REJECT","BLOCK")DEFAULT "PENDING",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER_REPORTING) REFERENCES TB_USER (ID_USER), 
    FOREIGN KEY (ID_USER_REPORTER) REFERENCES TB_USER (ID_USER), 
    FOREIGN KEY (ID_TYPE_USER_BLACKLIST) REFERENCES TB_TYPE_USER_BLACKLIST (ID_TYPE_USER_BLACKLIST)
);

CREATE TABLE IF NOT EXISTS TB_TYPE_USER_POST_BLACKLIST(
    ID_TYPE_USER_POST_BLACKLIST INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
);

CREATE TABLE IF NOT EXISTS TB_USER_POST_BLACKLIST(
    ID_USER_BLACKLIST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_POST INT,
    ID_USER_REPORTER VARCHAR(50),
    ID_TYPE_USER_POST_BLACKLIST INT,
    STATUS_BLACKLIST ENUM("PENDING", "REJECT","APPROVE")DEFAULT "PENDING",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER_POST) REFERENCES TB_USER_POST (ID_USER_POST),
    FOREIGN KEY (ID_USER_REPORTER) REFERENCES TB_USER (ID_USER), 
    FOREIGN KEY (ID_TYPE_USER_POST_BLACKLIST) REFERENCES TB_TYPE_USER_POST_BLACKLIST (ID_TYPE_USER_POST_BLACKLIST)
);


CREATE TABLE IF NOT EXISTS TB_TRAVEL(
    ID_TRAVEL INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
);

CREATE TABLE IF NOT EXISTS TB_USER_TRAVEL(
    ID_USER_TRAVEL INT AUTO_INCREMENT PRIMARY KEY,
    ID_TRAVEL INT,
    ID_USER VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_TRAVEL) REFERENCES TB_TRAVEL (ID_TRAVEL),
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);

CREATE TABLE IF NOT EXISTS TB_PROVINCE(
    ID_PROVINCE INT AUTO_INCREMENT PRIMARY KEY,
    NAME_TH VARCHAR(100) NOT NULL,
    NAME_EN VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
);

CREATE TABLE IF NOT EXISTS TB_USER_PROVINCE(
    ID_USER_PROVINCE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROVINCE INT,
    ID_USER VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PROVINCE) REFERENCES TB_PROVINCE (ID_PROVINCE),
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);

CREATE TABLE IF NOT EXISTS TB_FEEBACK_SYSTEM(
    ID_FEEBACK_SYSTEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50),
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);