CREATE TABLE IF NOT EXISTS TB_USER
(
    ID_USER VARCHAR(50) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PICTURE_PROFILE VARCHAR(50) NOT NULL,
    PICTURE_PROFILE_CONVERT VARCHAR(50) NOT NULL,
    PICTURE_PROFILE_COVER VARCHAR(50) NOT NULL,
    PICTURE_PROFILE_COVER_CONVERT VARCHAR(50) NOT NULL,
    ID_EMAIL VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ID_FACEBOOK VARCHAR(255) NOT NULL,
    TEL VARCHAR(10) NOT NULL,
    ID_LINE VARCHAR(20) NOT NULL,
    LOGINBY ENUM('system','email','facebook') DEFAULT "system",
    CREATED_AT DATE,
    UPDATED_AT DATE DEFAULT NULL,
    DELETED_AT DATE DEFAULT NULL
);


CREATE TABLE IF NOT EXISTS TB_USER_FAVORITE_COUNTRY
(
    ID_USER_FAVORITE_COUNTRY INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50),
    ID_COUNTRY INT,
    CREATED_AT DATE,
    UPDATED_AT DATE DEFAULT NULL,
    DELETED_AT DATE DEFAULT NULL,
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER),
    FOREIGN KEY (ID_COUNTRY) REFERENCES TB_COUNTRY (ID_COUNTRY)
);


CREATE TABLE IF NOT EXISTS TB_USER_ADDRESS
(
    ID_ADDRESS INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50),
    STREET VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    CREATED_AT DATE,
    UPDATED_AT DATE DEFAULT NULL,
    DELETED_AT DATE DEFAULT NULL,
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);

CREATE TABLE IF NOT EXISTS TB_USER_PREFERENCE
(
    ID_USER_PREFERENCE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50),
    ID_PREFERENCE INT,
    CREATED_AT DATE,
    UPDATED_AT DATE DEFAULT NULL,
    DELETED_AT DATE DEFAULT NULL,
    FOREIGN KEY (ID_PREFERENCE) REFERENCES TB_PREFERENCE (ID_PREFERENCE),
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);

