-- สร้างตารางเกี่ยวกับประเภทของบริษัท
CREATE TABLE IF NOT EXISTS TB_TYPE_COMPANY (
    ID_TYPE_COMPANY INT AUTO_INCREMENT PRIMARY KEY,
    NAME_COMPANY VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- วันที่สร้างบริษัท
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- วันที่แก้ไขข้อมูลล่าสุด
    DELETED_AT TIMESTAMP DEFAULT NULL
);

-- สร้างตารางเกี่ยวกับบริษัท
CREATE TABLE IF NOT EXISTS TB_COMPANIES (
    ID_COMPANY VARCHAR(50) PRIMARY KEY, -- รหัสบริษัท
    NAME_COMPANY VARCHAR(255) NOT NULL, -- ชื่อบริษัท
    ID_TYPE_COMPANY INT, -- รหัสประเภทบริษัท
    PHONE_NUMBER VARCHAR(20), -- เบอร์โทรศัพท์
    EMAIL VARCHAR(255), -- อีเมล์
    WEBSITE VARCHAR(255), -- เว็บไซต์
    FOUNDED_DATE DATE, -- วันที่ก่อตั้ง
    REGISTRATION_DATE DATE, -- วันที่ลงทะเบียน
    BUSINESS_LICENSE_NUMBER VARCHAR(50), -- เลขที่ใบอนุญาตธุรกิจ
    VAT_NUMBER VARCHAR(50), -- เลขประจำตัวผู้เสียภาษี
    ID_USER VARCHAR(50), -- รหัสเจ้าของบริษัท
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- วันที่สร้างบริษัท
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- วันที่แก้ไขข้อมูลล่าสุด
    DELETED_AT TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (ID_TYPE_COMPANY) REFERENCES TB_TYPE_COMPANY(ID_TYPE_COMPANY), -- เชื่อมโยงกับตาราง COMPANYTYPES
    FOREIGN KEY (ID_USER) REFERENCES TB_USERS(USER_ID) -- เชื่อมโยงกับตาราง USERS
);

-- สร้างตารางเกี่ยวกับที่อยู่ของบริษัท
CREATE TABLE IF NOT EXISTS TB_COMPANY_ADDRESS (
    ID_ADDRESS INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPANY VARCHAR(50),
    STREET VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- วันที่สร้างบริษัท
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- วันที่แก้ไขข้อมูลล่าสุด
    DELETED_AT TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (ID_COMPANY) REFERENCES TB_COMPANIES(ID_COMPANY)
);

-- สร้างตารางเกี่ยวกับโพสต์ของบริษัท
CREATE TABLE IF NOT EXISTS TB_COMPANY_POST (
    ID_COMPANY_POST INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPANY VARCHAR(50),
    POST VARCHAR(255) NOT NULL,
    POST_PICTURE VARCHAR(50) NOT NULL,
    POST_PICTURE_CONVERT VARCHAR(50) NOT NULL,
    PUBLIC BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- วันที่สร้างโพสต์
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- วันที่แก้ไขข้อมูลล่าสุด
    DELETED_AT TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (ID_COMPANY) REFERENCES TB_COMPANIES(ID_COMPANY)
);

-- สร้างตารางเกี่ยวกับการกดไลค์โพสต์ของบริษัท
CREATE TABLE IF NOT EXISTS TB_USER_LIKE_POST (
    ID_USER_LIKE_POST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50) NOT NULL,
    ID_COMPANY_POST INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- วันที่กดไลค์
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- วันที่แก้ไขข้อมูลล่าสุด
    DELETED_AT TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (ID_USER) REFERENCES TB_USERS(USER_ID),
    FOREIGN KEY (ID_COMPANY_POST) REFERENCES TB_COMPANY_POST(ID_COMPANY_POST)
);
