
CREATE TABLE IF NOT EXISTS TB_USER_GROUP_CAMPING_HOST(
    ID_USER_GROUP_CAMPING_HOST VARCHAR(50) PRIMARY KEY,
    ID_USER VARCHAR(50),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(50) NOT NULL,
    STATUE ENUM("PRIVATE","PUBLIC") DEFAULT "PRIVATE",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);



CREATE TABLE IF NOT EXISTS TB_USER_GROUP_CAMPING_MEMBER(
    ID_USER_GROUP_CAMPING_MEMBER INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_GROUP_CAMPING_HOST VARCHAR(50),
    ID_USER VARCHAR(50),
    ID_USER_INVITE VARCHAR(50),
    INVITE_BY ENUM("HOST","ADMIN","MEMBER","ME") DEFAULT "HOST" ,
    STATUS ENUM("PENDING","REJECT","APPROVE") DEFAULT "PENDING",
    AUTHORIZATION ENUM("MEMBER", "ADMIN") DEFAULT "MEMBER",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER),
    FOREIGN KEY (ID_USER_INVITE) REFERENCES TB_USER (ID_USER)
);

CREATE TABLE IF NOT EXISTS TB_GROUP_RESERVE_COMPANY
(
    ID_GROUP_RESERVE_COMPANY VARCHAR(50) PRIMARY KEY, -- 
    ID_USER_GROUP_CAMPING_HOST VARCHAR(50),
    ID_COMPANY VARCHAR(50),
    TOTAL_PRICE DECIMAL(10,2),
    STATUS_PAYMENT ENUM("PENDING","PAY") DEFAULT "PENDING",
    DESCRIPTION VARCHAR(100) NOT NULL,
    STATS ENUM("PENDING","REJECT","COMPLETE") DEFAULT "PENDING",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER_GROUP_CAMPING_HOST) REFERENCES TB_USER_GROUP_CAMPING_HOST (ID_USER_GROUP_CAMPING_HOST),
    FOREIGN KEY (ID_COMPANY) REFERENCES TB_COMPANY (ID_COMPANY)
);

CREATE TABLE IF NOT EXISTS TB_SEPARATE_GROUP_RESERVE_COMPANY
(
    ID_SEPARATE_GROUP_RESERVE_COMPAY INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_GROUP_CAMPING_HOST VARCHAR(50),
    ID_USER VARCHAR(50),
    PRICE DECIMAL(10,2),
    STATS ENUM("PENDING","PAY") DEFAULT "PENDING",
    DEADLINE_PAY_DATE TIMESTAMP DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER_GROUP_CAMPING_HOST) REFERENCES TB_USER_GROUP_CAMPING_HOST (ID_USER_GROUP_CAMPING_HOST)
);

CREATE TABLE IF NOT EXISTS TB_REFUND_GROUP_RESERVE_COMPANY
(
    ID_REFUND_GROUP_RESERVE_COMPANY INT AUTO_INCREMENT PRIMARY KEY,
    ID_GROUP_RESERVE_COMPANY VARCHAR(50),
    REJECT_BY ENUM("COMPANY","GROUP") DEFAULT "COMPANY",
    STATUS ENUM("PENDING","SUCCESS") DEFAULT "PENDING",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_GROUP_RESERVE_COMPANY) REFERENCES TB_GROUP_RESERVE_COMPANY (ID_GROUP_RESERVE_COMPANY)
);

CREATE TABLE IF NOT EXISTS TB_RATTING_GROUP_RESERVE_COMPANY
(
    ID_RATTING_GROUP_RESERVE_COMPANY INT AUTO_INCREMENT PRIMARY KEY,
    ID_GROUP_RESERVE_COMPANY VARCHAR(50),
    ID_USER VARCHAR(50),
    RATTING INT DEFAULT 5,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER),
    FOREIGN KEY (ID_GROUP_RESERVE_COMPANY) REFERENCES TB_GROUP_RESERVE_COMPANY (ID_GROUP_RESERVE_COMPANY)
);

CREATE TABLE IF NOT EXISTS TB_COMMENT_GROUP_RESERVE_COMPANY
(
    ID_RATTING_GROUP_RESERVE_COMPANY INT AUTO_INCREMENT PRIMARY KEY,
    ID_GROUP_RESERVE_COMPANY VARCHAR(50),
    ID_USER VARCHAR(50),
    COMMENT VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER),
    FOREIGN KEY (ID_GROUP_RESERVE_COMPANY) REFERENCES TB_GROUP_RESERVE_COMPANY (ID_GROUP_RESERVE_COMPANY)
);


