
CREATE TABLE IF NOT EXISTS TB_USER_GROUP_CAMPING_HOST(
    ID_USER_GROUP_CAMPING_HOST VARCHAR(50) PRIMARY KEY,
    ID_USER VARCHAR(50),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(50) NOT NULL,
    STATUE ENUM("PRIVATE","PUBLIC") DEFAULT "PRIVATE",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);

CREATE TABLE IF NOT EXISTS TB_USER_GROUP_CAMPING_MEMBER(
    ID_USER_GROUP_CAMPING_MEMBER INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_GROUP_CAMPING_HOST VARCHAR(50),
    ID_USER VARCHAR(50),
    ID_USER_INVITE VARCHAR(50),
    INVITE_BY ENUM("HOST","ADMIN","MEMBER","ME") DEFAULT "HOST" ,
    STATUS ENUM("PENDING","REJECT","APPROVE") DEFAULT "PENDING",
    AUTHORIZATION ENUM("MEMBER", "ADMIN") DEFAULT "MEMBER",
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT NULL, -- เพิ่มคอลัมน์สำหรับเก็บวันที่ลบข้อมูล
    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER),
    FOREIGN KEY (ID_USER_INVITE) REFERENCES TB_USER (ID_USER)
);